### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by vero1126nica** [vero1126nica/markdown-portfolio#2]
[ ] Turn on GitHub Pages  ­ 
[ ] Outline my portfolio  ­ 
[ ] Introduce myself to the world

**Comment by vero1126nica** [comment]
task list

**Comment by vero1126nica** [comment]
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world
